In [1]:
import pandas as pd

In [2]:
MUC_df = pd.read_csv('MUC_poi_df.csv')
PA_df = pd.read_csv('PA_poi_df.csv')

In [3]:
PA_compare_dict = { 
                'h3_code': PA_df.h3_source, 
                'total_poi': None,
                'station_count': None, 
                'Eat_and_Drink': None, 
                'Going_Out-Entertainment': None, 
                'Sights_and_Museums': None, 
                'Transport': None,
                'Accommodations': None, 
                'Shopping': None, 
                'Business_and_Services': None,
                'Facilities': None, 
                'Areas_and_Buildings': None}
PA_compare_df = pd.DataFrame(PA_compare_dict)

In [4]:
PA_compare_df = PA_compare_df.drop_duplicates()

In [5]:
def PA_stations_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_name == 'EV Charging Station')].count()
def PA_count_100_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Eat & Drink')].count()
def PA_count_200_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Going Out-Entertainment')].count()
def PA_count_300_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Sights and Museums')].count()
def PA_count_400_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Transport')].count()
def PA_count_500_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Accommodations')].count()
def PA_count_600_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Shopping')].count()
def PA_count_700_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Business and Services')].count()
def PA_count_800_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Facilities')].count()
def PA_count_900_in_h3(row):
    return PA_df[(PA_df.h3_source == row['h3_code']) & (PA_df.cat_definition == 'Areas and Buildings')].count()
def PA_total_poi(row):
    return row['Eat_and_Drink']+row['Going_Out-Entertainment']+row['Sights_and_Museums']+row['Transport']+row['Accommodations']+row['Shopping']+row['Business_and_Services']+row['Facilities']+row['Areas_and_Buildings']
def PA_area_high_low(row):
    if row['total_poi']<30:
        return 'Low-area'
    elif row['total_poi'] >= 30:
        return 'High-area'

In [6]:
PA_compare_df['station_count'] = PA_compare_df.apply(lambda row : PA_stations_in_h3(row), axis=1)
PA_compare_df['Eat_and_Drink'] = PA_compare_df.apply(lambda row : PA_count_100_in_h3(row), axis=1)
PA_compare_df['Going_Out-Entertainment'] = PA_compare_df.apply(lambda row : PA_count_200_in_h3(row), axis=1)
PA_compare_df['Sights_and_Museums'] = PA_compare_df.apply(lambda row : PA_count_300_in_h3(row), axis=1)
PA_compare_df['Transport'] = PA_compare_df.apply(lambda row : PA_count_400_in_h3(row), axis=1)
PA_compare_df['Accommodations'] = PA_compare_df.apply(lambda row : PA_count_500_in_h3(row), axis=1)
PA_compare_df['Shopping'] = PA_compare_df.apply(lambda row : PA_count_600_in_h3(row), axis=1)
PA_compare_df['Business_and_Services'] = PA_compare_df.apply(lambda row : PA_count_700_in_h3(row), axis=1)
PA_compare_df['Facilities'] = PA_compare_df.apply(lambda row : PA_count_800_in_h3(row), axis=1)
PA_compare_df['Areas_and_Buildings'] = PA_compare_df.apply(lambda row : PA_count_900_in_h3(row), axis=1)
PA_compare_df['total_poi'] = PA_compare_df.apply(lambda row : PA_total_poi(row), axis=1)
PA_compare_df['h3_area'] = PA_compare_df.apply(lambda row : PA_area_high_low(row), axis=1)

### Do it for Munich

In [7]:
MUC_compare_dict = { 
                'h3_code': MUC_df.h3_source, 
                'total_poi': None,
                'station_count': None, 
                'Eat_and_Drink': None, 
                'Going_Out-Entertainment': None, 
                'Sights_and_Museums': None, 
                'Transport': None,
                'Accommodations': None, 
                'Shopping': None, 
                'Business_and_Services': None,
                'Facilities': None, 
                'Areas_and_Buildings': None}
MUC_compare_df = pd.DataFrame(MUC_compare_dict)

In [8]:
MUC_compare_df = MUC_compare_df.drop_duplicates()

In [9]:
def MUC_stations_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_name == 'Ladestation f√ºr Elektrofahrzeuge')].count()
def MUC_count_100_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Eat & Drink')].count()
def MUC_count_200_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Going Out-Entertainment')].count()
def MUC_count_300_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Sights and Museums')].count()
def MUC_count_400_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Transport')].count()
def MUC_count_500_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Accommodations')].count()
def MUC_count_600_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Shopping')].count()
def MUC_count_700_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Business and Services')].count()
def MUC_count_800_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Facilities')].count()
def MUC_count_900_in_h3(row):
    return MUC_df[(MUC_df.h3_source == row['h3_code']) & (MUC_df.cat_definition == 'Areas and Buildings')].count()
def MUC_total_poi(row):
    return row['Eat_and_Drink']+row['Going_Out-Entertainment']+row['Sights_and_Museums']+row['Transport']+row['Accommodations']+row['Shopping']+row['Business_and_Services']+row['Facilities']+row['Areas_and_Buildings']
def MUC_area_high_low(row):
    if row['total_poi']<30:
        return 'Low-area'
    elif row['total_poi'] >= 30:
        return 'High-area'

In [10]:
MUC_compare_df['station_count'] = MUC_compare_df.apply(lambda row : MUC_stations_in_h3(row), axis=1)
MUC_compare_df['Eat_and_Drink'] = MUC_compare_df.apply(lambda row : MUC_count_100_in_h3(row), axis=1)
MUC_compare_df['Going_Out-Entertainment'] = MUC_compare_df.apply(lambda row : MUC_count_200_in_h3(row), axis=1)
MUC_compare_df['Sights_and_Museums'] = MUC_compare_df.apply(lambda row : MUC_count_300_in_h3(row), axis=1)
MUC_compare_df['Transport'] = MUC_compare_df.apply(lambda row : MUC_count_400_in_h3(row), axis=1)
MUC_compare_df['Accommodations'] = MUC_compare_df.apply(lambda row : MUC_count_500_in_h3(row), axis=1)
MUC_compare_df['Shopping'] = MUC_compare_df.apply(lambda row : MUC_count_600_in_h3(row), axis=1)
MUC_compare_df['Business_and_Services'] = MUC_compare_df.apply(lambda row : MUC_count_700_in_h3(row), axis=1)
MUC_compare_df['Facilities'] = MUC_compare_df.apply(lambda row : MUC_count_800_in_h3(row), axis=1)
MUC_compare_df['Areas_and_Buildings'] = MUC_compare_df.apply(lambda row : MUC_count_900_in_h3(row), axis=1)
MUC_compare_df['total_poi'] = MUC_compare_df.apply(lambda row : MUC_total_poi(row), axis=1)
MUC_compare_df['h3_area'] = MUC_compare_df.apply(lambda row : MUC_area_high_low(row), axis=1)

In [13]:
MUC_compare_df[MUC_compare_df.station_count == 0]

,h3_code,total_poi,station_count,Eat_and_Drink,Going_Out-Entertainment,Sights_and_Museums,Transport,Accommodations,Shopping,Business_and_Services,Facilities,Areas_and_Buildings,h3_area
0,891f8d7ad83ffff,23,0,0,1,0,2,2,2,11,5,0,Low-area
121,891f8d4584bffff,57,0,3,1,1,1,0,7,32,12,0,High-area
178,891f8d7b44bffff,37,0,1,0,0,3,2,3,22,6,0,High-area
215,891f8d450b3ffff,47,0,1,0,0,2,0,8,32,4,0,High-area
262,891f8d7b403ffff,51,0,1,0,0,1,2,10,25,12,0,High-area
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89381,891f8d44e3bffff,84,0,1,4,0,1,1,4,72,1,0,High-area
89465,891f8d7acc3ffff,22,0,0,1,0,0,0,2,19,0,0,Low-area
89487,891f8d45533ffff,21,0,0,0,0,0,0,2,18,1,0,Low-area
89508,891f8d73403ffff,1,0,0,0,0,0,0,0,1,0,0,Low-area
89509,891f8d446cbffff,15,0,0,0,0,1,3,1,10,0,0,Low-area

In [12]:
PA_compare_df.to_csv('PA_compare_df.csv', sep=',')
MUC_compare_df.to_csv('MUC_compare_df.csv', sep=',')